### ISSUE TITLE
Is there a ResNet version of this project?

### ISSUE THREAD

**Issue by TGISer** [Mid-Push/Moving-Semantic-Transfer-Network#3]
ResNet may improve performance, Will there be ResNet version later?
Thank you for your help!

**Comment by Mid-Push** [comment]
I did not run it extensively on ResNet due to limited GPU memory. There would be ResNet version in the future. But it may need a couple of months as I'm occupied by another project now.

Perhaps u can have a try by yourself firstly and I guess it would be quite simple: only two functions needed to be modified:
1. "inference", just replace the AlexNet with ResNet architectures.
2. "restore", modify the code to load pretrained ResNet instead of AlexNet.

Code on this may also help u. 
https://github.com/dgurkaynak/tensorflow-cnn-finetune.

**Comment by TGISer** [comment]
Thank you! I will try it !
